# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b456ac1f5bbd1b857b8648e40d7ae64ebe7f473045df48d720fcd16ca500484b2fb3f3567d74b1a94c74c340d8c021d69fb6bb1c1cec1b2fda71c395ad7b85f7

test:
  secret_key_base: 9031a7f9e745c917031123fc384aaa83e6f58d962cc5cb790a52257ef787ffe1e8e31db5006bfb36445d800e7a4c1928f3d15485a8dcdc06ee80a6fb5ccf5b59

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
